-- =====================================================================
-- SalesFixr — Core schema
-- Target: PostgreSQL 15+ (Neon free tier, or local Docker Postgres)
-- Run order: 001_schema.sql -> 002_seed_demo_clinic.sql
--
-- Conventions (see docs/02-NAMING-CONVENTIONS.md):
--   * snake_case everywhere, plural table names
--   * every business table carries tenant_id (multi-tenant from day 1)
--   * ids are uuid, generated by the database
--   * all timestamps are timestamptz, stored in UTC
--   * "wall clock" business config (hours, quiet hours) is stored as
--     local time + the tenant timezone, never as UTC
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";    -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "btree_gist";  -- needed by the no-double-booking constraint

-- ---------------------------------------------------------------------
-- ENUM types. Using enums (not free text) means the database itself
-- rejects a bad value the AI might hallucinate.
-- ---------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE channel_t AS ENUM ('test','messenger','whatsapp','sms','voice','web','instagram','email');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE direction_t AS ENUM ('inbound','outbound');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE actor_role_t AS ENUM ('customer','staff','owner','system');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE appointment_status_t AS ENUM ('held','booked','completed','cancelled','no_show');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE intent_t AS ENUM (
    'booking','reschedule','cancel','faq','pricing','hours','insurance',
    'human','medical_question','opt_out','owner_report','owner_schedule',
    'owner_contact_lookup','unknown'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE consent_purpose_t AS ENUM ('appointment','marketing','voice_recording');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE reminder_status_t AS ENUM ('pending','sent','skipped','failed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- =====================================================================
-- 1. TENANTS  — one row per clinic. The root of everything.
-- =====================================================================
CREATE TABLE IF NOT EXISTS tenants (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug            text NOT NULL UNIQUE,          -- 'demo_clinic'  (used in webhook payloads)
  display_name    text NOT NULL,                 -- 'SmileCare Dental'
  timezone        text NOT NULL DEFAULT 'America/New_York',
  is_active       boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- =====================================================================
-- 2. CLINIC_SETTINGS — the knobs the AI and the safety gate read.
--    One row per tenant. JSONB where the shape is genuinely flexible.
-- =====================================================================
CREATE TABLE IF NOT EXISTS clinic_settings (
  tenant_id            uuid PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
  clinic_name          text NOT NULL,
  address              text,
  phone_public         text,
  email_public         text,
  website              text,

  -- Safety gate inputs (deterministic, never decided by the LLM)
  quiet_hours_start    time NOT NULL DEFAULT '21:00',  -- local time
  quiet_hours_end      time NOT NULL DEFAULT '08:00',
  max_msgs_per_contact_per_day int NOT NULL DEFAULT 20,
  max_msgs_per_tenant_per_day  int NOT NULL DEFAULT 500,

  -- Booking policy
  min_lead_time_minutes    int NOT NULL DEFAULT 60,     -- can't book 5 min from now
  max_days_in_advance      int NOT NULL DEFAULT 90,
  slot_granularity_minutes int NOT NULL DEFAULT 30,
  hold_ttl_minutes         int NOT NULL DEFAULT 5,      -- temporary slot lock

  -- Integrations (ids only; secrets live in n8n credentials, never here)
  google_calendar_id   text,
  telegram_chat_id     text,
  messenger_page_id    text,

  reminder_offsets_hours int[] NOT NULL DEFAULT ARRAY[24, 2],

  extra                jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

-- =====================================================================
-- 3. SERVICES — what the clinic sells. Drives duration + price answers.
--    The AI must pick a service_code from THIS table, not invent one.
-- =====================================================================
CREATE TABLE IF NOT EXISTS services (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  code              text NOT NULL,               -- 'dental_cleaning'
  display_name      text NOT NULL,               -- 'Dental Cleaning'
  duration_minutes  int  NOT NULL DEFAULT 30,
  price_minor       int,                         -- store money in minor units (cents/poisha)
  currency          text NOT NULL DEFAULT 'USD',
  description       text,
  is_new_patient_ok boolean NOT NULL DEFAULT true,
  is_active         boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, code)
);

-- =====================================================================
-- 4. BUSINESS_HOURS — when the clinic is open, in LOCAL time.
--    0 = Sunday ... 6 = Saturday (matches JS getDay()).
-- =====================================================================
CREATE TABLE IF NOT EXISTS business_hours (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  weekday      smallint NOT NULL CHECK (weekday BETWEEN 0 AND 6),
  opens_at     time NOT NULL,
  closes_at    time NOT NULL,
  is_closed    boolean NOT NULL DEFAULT false,
  UNIQUE (tenant_id, weekday)
);

-- =====================================================================
-- 5. STAFF_USERS — who counts as owner/staff.
--    THIS TABLE IS HOW ROLE IS DECIDED. Deterministic lookup, never LLM.
--    A sender is 'owner'/'staff' only if their channel identity is here.
-- =====================================================================
CREATE TABLE IF NOT EXISTS staff_users (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id            uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  full_name            text NOT NULL,
  role                 actor_role_t NOT NULL DEFAULT 'staff',   -- 'owner' or 'staff'
  channel              channel_t NOT NULL,
  external_contact_id  text,          -- Messenger PSID / Telegram chat id
  phone_e164           text,          -- for SMS/WhatsApp/voice
  email                text,
  is_active            boolean NOT NULL DEFAULT true,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS staff_users_ident_uq
  ON staff_users (tenant_id, channel, external_contact_id)
  WHERE external_contact_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS staff_users_phone_idx ON staff_users (tenant_id, phone_e164);

-- =====================================================================
-- 6. CONTACTS — patients. One row per human per tenant.
-- =====================================================================
CREATE TABLE IF NOT EXISTS contacts (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id            uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  full_name            text,
  phone_e164           text,                      -- '+12125550199' — always E.164
  email                text,
  preferred_channel    channel_t,
  timezone             text,                      -- falls back to tenant timezone
  locale               text DEFAULT 'en',
  marketing_consent    boolean NOT NULL DEFAULT false,
  appointment_consent  boolean NOT NULL DEFAULT true,
  opted_out            boolean NOT NULL DEFAULT false,
  opted_out_at         timestamptz,
  is_new_patient       boolean NOT NULL DEFAULT true,
  notes                text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS contacts_phone_uq
  ON contacts (tenant_id, phone_e164) WHERE phone_e164 IS NOT NULL;
CREATE INDEX IF NOT EXISTS contacts_tenant_idx ON contacts (tenant_id);

-- =====================================================================
-- 7. CONTACT_IDENTITIES — one contact can arrive on many channels.
--    This is the lookup table WF-01 uses to resolve "who is this?".
-- =====================================================================
CREATE TABLE IF NOT EXISTS contact_identities (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id            uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id           uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  channel              channel_t NOT NULL,
  external_contact_id  text NOT NULL,             -- Messenger PSID, phone, etc.
  display_name         text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, channel, external_contact_id)
);
CREATE INDEX IF NOT EXISTS contact_identities_contact_idx ON contact_identities (contact_id);

-- =====================================================================
-- 8. CONSENTS — append-only consent ledger. Never UPDATE, only INSERT.
--    contacts.marketing_consent is the fast cached flag; this is proof.
-- =====================================================================
CREATE TABLE IF NOT EXISTS consents (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id   uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  channel      channel_t NOT NULL,
  purpose      consent_purpose_t NOT NULL,
  consent      boolean NOT NULL,
  source       text NOT NULL,                     -- 'messenger_opt_in', 'stop_keyword', 'web_form'
  evidence     jsonb NOT NULL DEFAULT '{}'::jsonb,
  captured_at  timestamptz NOT NULL DEFAULT now(),
  revoked_at   timestamptz
);
CREATE INDEX IF NOT EXISTS consents_contact_idx ON consents (tenant_id, contact_id, purpose);

-- =====================================================================
-- 9. CONVERSATIONS — one row per message, in or out. Short retention.
-- =====================================================================
CREATE TABLE IF NOT EXISTS conversations (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id            uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id           uuid REFERENCES contacts(id) ON DELETE CASCADE,
  staff_user_id        uuid REFERENCES staff_users(id) ON DELETE SET NULL,
  actor_role           actor_role_t NOT NULL DEFAULT 'customer',
  channel              channel_t NOT NULL,
  direction            direction_t NOT NULL,
  external_message_id  text,
  body                 text,
  message_type         text NOT NULL DEFAULT 'text',
  intent               intent_t,
  ai_payload           jsonb,                     -- the structured JSON the LLM returned
  created_at           timestamptz NOT NULL DEFAULT now()
);
-- Idempotency: Meta retries webhooks. This stops duplicate processing.
CREATE UNIQUE INDEX IF NOT EXISTS conversations_external_uq
  ON conversations (tenant_id, channel, external_message_id)
  WHERE external_message_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS conversations_thread_idx
  ON conversations (tenant_id, contact_id, created_at DESC);

-- =====================================================================
-- 10. APPOINTMENTS — the booking record.
--     The EXCLUDE constraint is what makes double-booking IMPOSSIBLE
--     at the database level, regardless of what the AI or a race does.
-- =====================================================================
CREATE TABLE IF NOT EXISTS appointments (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id        uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  service_id        uuid REFERENCES services(id) ON DELETE SET NULL,
  service_code      text NOT NULL,
  start_time        timestamptz NOT NULL,
  end_time          timestamptz NOT NULL,
  status            appointment_status_t NOT NULL DEFAULT 'held',
  hold_expires_at   timestamptz,                  -- set while status = 'held'
  calendar_event_id text,
  source_channel    channel_t NOT NULL,
  booked_by_role    actor_role_t NOT NULL DEFAULT 'customer',
  cancel_reason     text,
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT appointments_time_valid CHECK (end_time > start_time),

  -- No two live appointments for the same clinic may overlap in time.
  -- 'held' rows count, so a 5-minute hold really blocks the slot.
  CONSTRAINT appointments_no_overlap EXCLUDE USING gist (
    tenant_id WITH =,
    tstzrange(start_time, end_time, '[)') WITH &&
  ) WHERE (status IN ('held','booked'))
);
CREATE INDEX IF NOT EXISTS appointments_lookup_idx
  ON appointments (tenant_id, start_time) WHERE status IN ('held','booked');
CREATE INDEX IF NOT EXISTS appointments_contact_idx
  ON appointments (tenant_id, contact_id, start_time DESC);

-- =====================================================================
-- 11. REMINDERS — one row per reminder we intend to send.
--     Created when an appointment is booked; WF-04 drains this table.
-- =====================================================================
CREATE TABLE IF NOT EXISTS reminders (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  appointment_id  uuid NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  contact_id      uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  offset_hours    int NOT NULL,
  send_at         timestamptz NOT NULL,
  channel         channel_t NOT NULL,
  status          reminder_status_t NOT NULL DEFAULT 'pending',
  sent_at         timestamptz,
  skip_reason     text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (appointment_id, offset_hours)
);
CREATE INDEX IF NOT EXISTS reminders_due_idx
  ON reminders (status, send_at) WHERE status = 'pending';

-- =====================================================================
-- 12. AI_PERSONAS — the role-aware brain config.
--     One row per (tenant, role). WF-02 loads the row matching the
--     role the SAFETY GATE decided, then feeds it to the model.
--     Changing how the AI behaves = an UPDATE here, not a workflow edit.
-- =====================================================================
CREATE TABLE IF NOT EXISTS ai_personas (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  role              actor_role_t NOT NULL,
  system_prompt     text NOT NULL,
  allowed_intents   intent_t[] NOT NULL,
  allowed_tools     text[] NOT NULL DEFAULT '{}',  -- 'check_availability','book','cancel','lookup_contact','daily_report'
  data_scope        text NOT NULL DEFAULT 'own',   -- 'own' = only this contact's data | 'tenant' = all clinic data
  max_reply_chars   int NOT NULL DEFAULT 600,
  is_active         boolean NOT NULL DEFAULT true,
  updated_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, role)
);

-- =====================================================================
-- 13. FAQS — grounded answers so the model doesn't invent clinic policy.
-- =====================================================================
CREATE TABLE IF NOT EXISTS faqs (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  question     text NOT NULL,
  answer       text NOT NULL,
  tags         text[] NOT NULL DEFAULT '{}',
  visible_to   actor_role_t[] NOT NULL DEFAULT ARRAY['customer','staff','owner']::actor_role_t[],
  is_active    boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- =====================================================================
-- 14. AUDIT_LOGS — every gate decision and every tool call.
--     This is what you show a portfolio reviewer to prove the system
--     is deterministic and traceable.
-- =====================================================================
CREATE TABLE IF NOT EXISTS audit_logs (
  id            bigserial PRIMARY KEY,
  tenant_id     uuid REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id    uuid REFERENCES contacts(id) ON DELETE SET NULL,
  workflow      text NOT NULL,                    -- 'WF-01', 'WF-03'
  action        text NOT NULL,                    -- 'safety_gate', 'book_appointment'
  status        text NOT NULL,                    -- 'ok' | 'blocked' | 'error'
  reason_code   text,                             -- 'opted_out', 'quiet_hours', 'slot_taken'
  correlation_id text,                            -- ties one inbound message to all its rows
  details       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_logs_corr_idx ON audit_logs (correlation_id);
CREATE INDEX IF NOT EXISTS audit_logs_recent_idx ON audit_logs (tenant_id, created_at DESC);

-- =====================================================================
-- 15. PROCESSED_EVENTS — webhook idempotency guard.
--     Meta/Twilio retry aggressively. Insert here first; on conflict, stop.
-- =====================================================================
CREATE TABLE IF NOT EXISTS processed_events (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid REFERENCES tenants(id) ON DELETE CASCADE,
  channel       channel_t NOT NULL,
  event_key     text NOT NULL,                    -- provider message id
  received_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (channel, event_key)
);

-- =====================================================================
-- updated_at auto-touch
-- =====================================================================
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['tenants','clinic_settings','contacts','appointments']
  LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS %I_touch ON %I; CREATE TRIGGER %I_touch
       BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION touch_updated_at();',
      t, t, t, t);
  END LOOP;
END $$;
